name: dotnet package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore src/
      - name: Test with dotnet
        run: dotnet test --no-restore --logger trx --results-directory "TestResults" src/ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../../TestResults/"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results
          path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rosenkolev/dev-terminals
          files: TestResults/coverage.opencover.xml
      - name: Create the Terminal package with symbols
        run: dotnet pack --no-restore --configuration Release src/Dev.Terminals/Dev.Terminals.csproj --include-symbols
      - name: Clear nupkg packages for another build with README
        run: rm src/*/bin/Release/*.nupkg
      - name: Create the Terminal package with README
        run: dotnet pack --no-restore --configuration Release src/Dev.Terminals/Dev.Terminals.csproj -p:PACK_README=true
      - name: Publish the Terminal package to nuget.org
        run: dotnet nuget push src/Dev.Terminals/bin/Release/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
